(function(global){
'use strict';
const SOH_ORDERED_COLS=['SOH_310_MELBOURNE','SOH_315_HOBART','SOH_330_SYDNEY','SOH_335_NEWCASTLE','SOH_340_ADELAIDE','SOH_350_BRISBANE','SOH_353_BRISBANE_4PL','SOH_355_TOWNSVILLE','SOH_370_PERTH'];
const DESC2_NOISE_PATTERNS=[/\*\*SELL\s*THROUGH\s*\*\*/gi,/\*\*\s*SELL\s*THROUGH\s*\*\*/gi,/\*SELL\s*THRU.*?\*/gi,/\*\*\s*OBSOLETE\s*MANUFACTURER\s*\*\*/gi,/\*\*OBSOLETE\s*\*\*/gi,/\*AVL\s*[\d.]+\*/gi,/\*\*\s*SELL\s*THRU.*?\*\*/gi];
const CH2_COLUMN_ALIASES={vendor:['Vendor Name','Vendor','Supplier Name','Supplier'],brand:['Brand','Brand Name'],item_code:['PGC Item Code','Item Code','CH2 Code','Product Code','Product ID','SKU Code','SKU','Item Number','Item No'],description_1:['Description 1','Description','Item Description','Product Description'],description_2:['Description 2','Secondary Description'],long_description:['Long Description','Long Product Description','Full Description'],wholesale:['Wholesale ex GST','Wholesale','Wholesale Price ex GST','WSP ex GST','WS ex GST','Cost ex GST'],rrp:['RRP inc GST','RRP','Recommended Retail Price','Retail Price'],gst:['GST Y N','GST Y/N','GST'],barcode:['Bar Code','Barcode','EAN','EAN13','GTIN','UPC','GI Cross Reference','Cross Reference'],class_type:['Class Type'],product_class:['Product Class'],stock_type:['Stock Type']};
const WEIGHTS={item_code:8,brand:7,barcode:6,wholesale:6,rrp:6,long_description:4,description_1:3,description_2:2,vendor:2,gst:2,class_type:1,product_class:1,stock_type:1};
const SUPPLIER_IMPORT_HEADERS=['INDEX','POS SUPPLIER NAME','POS SUPPLIER NUMBER','SUP BARCODE','SUP BRAND','SUP SUB ID','SUP PRODUCT','SUP UNITS IN PACK','SUP MIN ORDER WS','SUP WS EXGST','SUP RRP INC GST','SUP GST','SUP STOCK IN','SUP DISCOUNT PRICE','POS MEMBER','STATUS'];
function cleanExcelText(v){if(v===null||v===undefined)return '';let s=String(v).replace(/_x00(0[0-8BCEF]|1[0-9A-F])_/gi,'');return s.replace(/[\x00-\x08\x0B\x0C\x0E-\x1F]/g,'');}
function cleanHeaderName(name,prefix='CH2_'){if(name===null||name===undefined||!String(name).trim())return '';let s=cleanExcelText(name).trim().replace(/[\r\n]+/g,' ').replace(/[^\w\s]/g,'').replace(/\s+/g,'_').toUpperCase();return prefix+s;}
function normalizeHeaderKey(value){if(value===null||value===undefined)return '';let s=cleanExcelText(value).trim().toUpperCase();if(s.startsWith('CH2_'))s=s.slice(4);s=s.replace(/&/g,' AND ').replace(/[_\r\n]+/g,' ').replace(/[^A-Z0-9]+/g,' ');return s.replace(/\s+/g,' ').trim();}
function aliases(role){return (CH2_COLUMN_ALIASES[role]||[]).map(normalizeHeaderKey)}
function headerMatchesRole(value,role){const key=normalizeHeaderKey(value);if(!key)return false;const as=aliases(role);if(as.includes(key))return true;const toks=new Set(key.split(' '));if(role==='item_code')return (toks.has('ITEM')&&toks.has('CODE'))||(toks.has('PRODUCT')&&toks.has('CODE'))||['CH2 CODE','PGC CODE'].includes(key);if(role==='barcode')return toks.has('BARCODE')||(toks.has('BAR')&&toks.has('CODE'))||['EAN','EAN13','GTIN','UPC'].some(t=>toks.has(t));if(role==='brand')return toks.has('BRAND');if(role==='wholesale')return toks.has('WHOLESALE')||(toks.has('COST')&&toks.has('GST'));if(role==='rrp')return toks.has('RRP')||(toks.has('RETAIL')&&toks.has('PRICE'));if(role==='long_description')return toks.has('LONG')&&toks.has('DESCRIPTION');if(role==='description_1')return ['DESCRIPTION','DESCRIPTION 1','ITEM DESCRIPTION','PRODUCT DESCRIPTION'].includes(key);if(role==='description_2')return key==='DESCRIPTION 2';if(role==='gst')return key==='GST'||key.startsWith('GST ');return false;}
function resolveCh2Columns(headers){const out={};for(const role of Object.keys(CH2_COLUMN_ALIASES)){let found=null;for(const a of aliases(role)){for(let i=0;i<headers.length;i++){if(normalizeHeaderKey(headers[i])===a){found=i;break}}if(found!==null)break}if(found===null){for(let i=0;i<headers.length;i++){if(headerMatchesRole(headers[i],role)){found=i;break}}}if(found!==null)out[role]=found;}return out;}
function scoreHeaderRow(row){const cleaned=(row||[]).map(v=>v===null||v===undefined?'':String(v).trim());const resolved=resolveCh2Columns(cleaned);let score=Object.keys(resolved).reduce((s,r)=>s+(WEIGHTS[r]||0),0);if(resolved.item_code!==undefined&&resolved.brand!==undefined)score+=8;if(resolved.item_code!==undefined&&resolved.barcode!==undefined)score+=5;if(resolved.wholesale!==undefined&&resolved.rrp!==undefined)score+=8;return {score,resolved};}
function selectBestSheet(sheets){let best={sheetName:'',rows:[],headerIdx:-1,score:-1};for(const sh of sheets){let ss=-1,hi=-1;for(let i=0;i<Math.min(120,sh.rows.length);i++){const x=scoreHeaderRow(sh.rows[i]);if(x.score>ss){ss=x.score;hi=i}}if(ss>best.score)best={sheetName:sh.name,rows:sh.rows,headerIdx:hi,score:ss};}return best;}
function normalizeBarcode(v){if(v===null||v===undefined)return '';let d=String(v).replace(/\D/g,'');if(!d||d.length>14)return '';if(d.length===14)d=d.slice(1);if(d.length<13)d=d.padStart(13,'0');return d.length===13?d:'';}
function pyRound2Number(n){
  if(!Number.isFinite(n)||n===0)return n;
  // Exact IEEE-754 binary64 -> rational, then Python-compatible ties-to-even rounding at 2 dp.
  const buf=new ArrayBuffer(8),dv=new DataView(buf);dv.setFloat64(0,n,false);
  const hi=dv.getUint32(0,false),lo=dv.getUint32(4,false);
  const neg=(hi>>>31)!==0,exp=(hi>>>20)&0x7ff;
  let frac=(BigInt(hi&0xfffff)<<32n)|BigInt(lo),mant,shift;
  if(exp===0){mant=frac;shift=-1074;}else{mant=(1n<<52n)|frac;shift=exp-1023-52;}
  let num=mant*100n,den=1n;
  if(shift>=0)num <<= BigInt(shift); else den <<= BigInt(-shift);
  let q=num/den,r=num%den;const twice=r*2n;
  if(twice>den || (twice===den && (q&1n)===1n)) q+=1n;
  const out=Number(q)/100;return neg?-out:out;
}
function smartCellValue(v,isBarcode=false,isPrice=false){if(v===null||v===undefined)return '';if(isBarcode)return normalizeBarcode(v);if(isPrice){const n=Number(v);return Number.isFinite(n)?pyRound2Number(n):v}return cleanExcelText(v).trim();}
function identifySpecialColumns(headers){const r=resolveCh2Columns(headers);const price=[];for(const role of ['wholesale','rrp'])if(r[role]!==undefined&&!price.includes(r[role]))price.push(r[role]);headers.forEach((h,i)=>{const k=normalizeHeaderKey(h);if(['WHOLESALE','RRP','PRICE','COST'].some(x=>k.includes(x))&&!price.includes(i))price.push(i)});return {barcode:r.barcode,itemCode:r.item_code,brand:r.brand,price};}
function parseSupplierSheets(sheets){const sel=selectBestSheet(sheets);if(!sel.rows.length||sel.headerIdx<0||sel.score<18)throw new Error('Could not identify a valid CH2 pricelist worksheet/header.');const raw=sel.rows[sel.headerIdx]||[];const data=sel.rows.slice(sel.headerIdx+1);let start=0;for(let i=0;i<raw.length;i++){if(raw[i]!==null&&raw[i]!==undefined&&String(raw[i]).trim()){start=i;break}}const headers=[],map=new Map();for(let i=start;i<raw.length;i++){const h=cleanHeaderName(raw[i],'CH2_');if(h){headers.push(h);map.set(i,h)}}const rows=[];for(const row of data){const aligned=[];for(let i=0;i<raw.length;i++)if(map.has(i))aligned.push(i<row.length?row[i]:'');if(aligned.some(c=>c!==null&&c!==undefined&&String(c).trim()))rows.push(aligned)}return {headers,rows,metadata:{selected_sheet:sel.sheetName,header_row_index:sel.headerIdx,header_score:sel.score}};}
function processSupplier(headers,rows,brandMapping){const sp=identifySpecialColumns(headers);if(sp.barcode===undefined||sp.brand===undefined||sp.itemCode===undefined)throw new Error('Critical CH2 columns not found for processing.');let outHeaders=['CH2_INDEX','CH2_MASTER_BRAND','CH2_MASTER_BARCODE',...headers],subs=0;let processed=[];rows.forEach((row,idx)=>{const original=cleanExcelText(sp.brand<row.length?row[sp.brand]:'').trim();const master=brandMapping&&brandMapping.has(original.toUpperCase())?brandMapping.get(original.toUpperCase()):original;if(master!==original&&original)subs++;const cells=row.slice(0,headers.length).map((c,i)=>smartCellValue(c,i===sp.barcode,sp.price.includes(i)));while(cells.length<headers.length)cells.push('');processed.push([idx+1,master,normalizeBarcode(sp.barcode<row.length?row[sp.barcode]:''),...cells]);});const helper='CH2_CH2_ITEM_CODE';if(!outHeaders.includes(helper)){const src=sp.itemCode+3,insert=src+1;outHeaders=[...outHeaders.slice(0,insert),helper,...outHeaders.slice(insert)];processed=processed.map(r=>[...r.slice(0,insert),cleanExcelText(src<r.length?r[src]:'').trim(),...r.slice(insert)]);}return {headers:outHeaders,rows:processed,brandSubstitutions:subs};}
function cleanDesc2(v){if(v===null||v===undefined||['','nan'].includes(String(v).trim().toLowerCase()))return '';let s=cleanExcelText(v).trim();for(const re of DESC2_NOISE_PATTERNS)s=s.replace(re,'');return s.trim();}
function enhanced(d1,d2,longv){const h=longv===null||longv===undefined?'':cleanExcelText(longv).trim();if(h&&h.toLowerCase()!=='nan')return h;const f=d1===null||d1===undefined?'':cleanExcelText(d1).trim(),g=cleanDesc2(d2);return g?`${f} ${g}`.trim():f;}
function addEnhanced(headers,rows){const i1=headers.indexOf('CH2_DESCRIPTION_1'),i2=headers.indexOf('CH2_DESCRIPTION_2'),il=headers.indexOf('CH2_LONG_DESCRIPTION');if(il<0)return {headers,rows,fallbackCount:0};const ins=il+1,nh=[...headers.slice(0,ins),'CH2_LONG_DESCRIPTION_ENHANCED',...headers.slice(ins)];let fallback=0;const nr=rows.map(r=>{const lv=il<r.length?r[il]:'';const raw=lv===null||lv===undefined?'':String(lv).trim();if(!raw||raw.toLowerCase()==='nan')fallback++;const e=enhanced(i1>=0&&i1<r.length?r[i1]:'',i2>=0&&i2<r.length?r[i2]:'',lv);return [...r.slice(0,ins),e,...r.slice(ins)]});return {headers:nh,rows:nr,fallbackCount:fallback};}
function cleanItemCode(v){if(v===null||v===undefined||String(v).trim()===''||String(v)==='nan')return '';const d=[...String(v).trim()].filter(c=>/\d/.test(c)).join('');return d.replace(/^0+/,'')||'0';}
const BRANCH_MAP={'310 - Melbourne':'SOH_310_MELBOURNE','315 - Hobart':'SOH_315_HOBART','330 - Sydney':'SOH_330_SYDNEY','335 - Newcastle':'SOH_335_NEWCASTLE','340 - Adelaide':'SOH_340_ADELAIDE','350 - Brisbane':'SOH_350_BRISBANE','353 - Brisbane 4PL':'SOH_353_BRISBANE_4PL','355 - Townsville':'SOH_355_TOWNSVILLE','370 - Perth':'SOH_370_PERTH'};
function parseSoh(rows){let hi=-1,headers=[];for(let i=0;i<Math.min(120,rows.length);i++){const vals=(rows[i]||[]).map(v=>v===null||v===undefined?'':String(v).trim()),low=vals.map(v=>v.toLowerCase());if(low.includes('branch')&&low.includes('code')&&['quantity on hand','qty on hand','on hand','quantity'].some(q=>low.includes(q))){hi=i;headers=vals;break}}if(hi<0)throw new Error('Could not detect SOH header row');const find=subs=>headers.map(x=>x.toLowerCase()).findIndex(h=>subs.some(s=>h.includes(s)));const cb=find(['branch']),cc=find(['code']),cq=find(['quantity on hand','qty on hand','on hand','quantity']);const data=[];for(const row of rows.slice(hi+1)){if(!(row||[]).some(c=>c!==null&&c!==undefined&&String(c).trim()))continue;const code=cc>=0&&cc<row.length?row[cc]:'';if(String(code??'').trim())data.push({branch:cb>=0&&cb<row.length?row[cb]:'',code,qty:cq>=0&&cq<row.length?row[cq]:''});}return {data,headerIdx:hi,indices:{branch:cb,code:cc,qty:cq}};}
function buildSohLookup(data){const lookup=new Map(),stats={};Object.keys(BRANCH_MAP).forEach(b=>stats[b]=0);for(const r of data){const code=cleanItemCode(r.code);if(!code)continue;const branch=String(r.branch??'').trim();let q=0;const n=Number(r.qty);if(r.qty&&Number.isFinite(n))q=Math.trunc(n);if(BRANCH_MAP[branch]){if(!lookup.has(code))lookup.set(code,{});const o=lookup.get(code),col=BRANCH_MAP[branch];o[col]=(o[col]||0)+q;stats[branch]++;}}return {lookup,stats};}
function augmentSoh(headers,rows,lookup){let idx=headers.indexOf('CH2_CH2_ITEM_CODE');if(idx<0){const r=resolveCh2Columns(headers);idx=r.item_code===undefined?-1:r.item_code;}if(idx<0)return {headers,rows};const add=SOH_ORDERED_COLS.filter(c=>!headers.includes(c)),nh=[...headers,...add,'SOH_TOTAL'];const nr=rows.map(r=>{const o=lookup.get(cleanItemCode(idx<r.length?r[idx]:''))||{},vals=add.map(c=>Math.trunc(Number(o[c]||0))),total=vals.reduce((a,b)=>a+b,0);return [...r,...vals,total]});return {headers:nh,rows:nr};}
function normalizeProductCode(v){if(v===null||v===undefined)return '';let s=cleanExcelText(v).trim().replace(/^'/,'');if(!s||['nan','none'].includes(s.toLowerCase()))return '';if(/^[+-]?\d+(?:\.0+)?$/.test(s)){let d=s.split('.')[0].replace(/^\+/,'');if(d.startsWith('-'))return d;return d.replace(/^0+/,'')||'0';}return s.replace(/\s+/g,'').toUpperCase();}
function isBoxHeader(row){const vals=(row||[]).map(v=>v===null||v===undefined?'':String(v).toLowerCase().trim());return vals.some(v=>v.includes('product code'))&&vals.some(v=>v.includes('width')||v.includes('depth')||v.includes('height'));}
function parseBoxSheets(sheets){const records=[],canonical=[],skipped=[];let loaded=0;for(const sh of sheets){let hi=-1;for(let i=0;i<Math.min(120,sh.rows.length);i++){if(isBoxHeader(sh.rows[i])){hi=i;break}}if(hi<0){skipped.push(sh.name);continue}const raw=sh.rows[hi]||[],map=new Map();raw.forEach((h,i)=>{const c=cleanHeaderName(h,'BOX_');if(c){map.set(i,c);if(!canonical.includes(c))canonical.push(c)}});if(![...map.values()].includes('BOX_PRODUCT_CODE')){skipped.push(sh.name);continue}loaded++;for(const rr of sh.rows.slice(hi+1)){const rec={};for(const [i,h] of map.entries())rec[h]=i<rr.length?rr[i]:'';const key=normalizeProductCode(rec.BOX_PRODUCT_CODE);if(!key||key==='PRODUCTCODE')continue;records.push(rec)}}return {headers:canonical,rows:records.map(r=>canonical.map(h=>r[h]??'')),metadata:{sheets_loaded:loaded,sheets_skipped:skipped,record_count:records.length}};}
function mergeBox(mainHeaders,mainRows,boxHeaders,boxRows){if(!boxHeaders.length||!boxRows.length)return {headers:mainHeaders,rows:mainRows,matched:0};const pci=boxHeaders.indexOf('BOX_PRODUCT_CODE');if(pci<0)return {headers:mainHeaders,rows:mainRows,matched:0};const lookup=new Map(),idxLookup=new Map();boxRows.forEach((row,j)=>{const key=normalizeProductCode(pci<row.length?row[pci]:'');if(!key)return;if(!lookup.has(key)){lookup.set(key,row.slice());idxLookup.set(key,j+1)}else{const ex=lookup.get(key);row.forEach((v,i)=>{const ev=i<ex.length?ex[i]:'';if((ev===null||ev===undefined||String(ev).trim()==='')&&v!==null&&v!==undefined&&String(v)!==''){while(ex.length<=i)ex.push('');ex[i]=v}})}});const names=['CH2_PGC_ITEM_CODE','CH2_CH2_ITEM_CODE','CH2_ITEM_CODE'],indices=names.filter(h=>mainHeaders.includes(h)).map(h=>[h,mainHeaders.indexOf(h)]);if(!indices.length)return {headers:mainHeaders,rows:mainRows,matched:0};const add=['BOX_INDEX',...boxHeaders],nh=[...mainHeaders,...add],blank=add.map(()=> '');let matched=0;const nr=mainRows.map(r=>{let key='';for(const [,i] of indices){const k=normalizeProductCode(i<r.length?r[i]:'');if(k&&lookup.has(k)){key=k;break}}if(key){matched++;return [...r,idxLookup.get(key),...lookup.get(key)]}return [...r,...blank]});return {headers:nh,rows:nr,matched};}
function getVal(headers,row,names,def=''){for(const n of names){const i=headers.indexOf(n);if(i>=0&&i<row.length)return row[i]===null||row[i]===undefined?'':row[i]}return def;}
function cleanCarton(v){if(v===null||v===undefined||String(v).trim()==='')return '';const n=Number(String(v).trim());if(Number.isFinite(n))return Number.isInteger(n)?n:n;return String(v).trim();}
function buildSupplierImport(headers,rows){return rows.map(r=>{const carton=cleanCarton(getVal(headers,r,['BOX_HOW_MANY_IN_A_CT','BOX_HOW_MANY_IN_A_CARTON','BOX_CARTON_QTY','BOX_CT_QTY']));return [getVal(headers,r,['CH2_INDEX']),'OBORNE / CH2',134,getVal(headers,r,['CH2_MASTER_BARCODE']),getVal(headers,r,['CH2_MASTER_BRAND']),getVal(headers,r,['CH2_PGC_ITEM_CODE','CH2_CH2_ITEM_CODE','CH2_ITEM_CODE']),getVal(headers,r,['CH2_LONG_DESCRIPTION_ENHANCED','CH2_LONG_DESCRIPTION']),'',carton,getVal(headers,r,['CH2_WHOLESALE_EX_GST']),getVal(headers,r,['CH2_RRP_INC_GST']),getVal(headers,r,['CH2_GST_YN']),'','','',''];});}
const api={SOH_ORDERED_COLS,SUPPLIER_IMPORT_HEADERS,cleanExcelText,cleanHeaderName,normalizeHeaderKey,resolveCh2Columns,scoreHeaderRow,selectBestSheet,normalizeBarcode,parseSupplierSheets,processSupplier,addEnhanced,parseSoh,buildSohLookup,augmentSoh,normalizeProductCode,parseBoxSheets,mergeBox,buildSupplierImport};
if(typeof module!=='undefined'&&module.exports)module.exports=api;global.CH2Core=api;
})(typeof window!=='undefined'?window:globalThis);
