(function(){'use strict';
const VERSION='v21.4.0', CH2V='v1.0.0', UHPV='v1.0.1', MASTERV='v2.2.0', POSV='v5.0.1';
const C=window.CH2Core,U=window.UHPCore,M=window.MasterCore;
const $=s=>document.querySelector(s), state={files:{},outputs:new Map(),models:{},urls:[],validation:{},stageStatus:{}};
const FILES=[
 ['stock','BrowseStockItems1','Required · POS stock export (.XLS / .XLSX)',true,'.xls,.xlsx,.xlsm,.csv','POS Inputs'],
 ['template','Product Insert Template','Required · POS product template (.XLS / .XLSX)',true,'.xls,.xlsx,.xlsm,.csv','POS Inputs'],
 ['brand','Brand Abbreviation','Optional · shared brand mapping for POS, CH2 and Unique',false,'.xls,.xlsx,.xlsm','Universal / Shared'],
 ['ch2','ParagonCare / CH2 Pricelist','Required · monthly CH2 / ParagonCare pricelist',true,'.xlsx,.xlsm,.xls','Oborne / CH2 Inputs'],
 ['soh','CR666a Stock On Hand','Required · current Oborne / CH2 stock on hand',true,'.xlsx,.xlsm,.xls','Oborne / CH2 Inputs'],
 ['box','Weight & Dimensions','Optional · CH2 carton / dimensions data',false,'.xlsx,.xlsm,.xls','Oborne / CH2 Inputs'],
 ['uhp','Unique / UHP Product Export','Required · UHP product/pricelist export',true,'.xlsx,.xlsm,.xls,.csv','Unique / UHP Inputs'],
 ['discounts','Ongoing Discounts','Optional · discount matrix used by Combined Master pricing',false,'.xlsx,.xlsm,.xls','Combined Master Inputs'],
 ['availability','To-Order / Availability','Optional · Supplier Number / PLU-SKU / Qty-Units CSV or Excel used for fulfilment and order output',false,'.csv,.txt,.xlsx,.xlsm,.xls','Combined Master Inputs']
];
const STAGES=[
 {id:'pos',n:1,title:'POS DATABASE',ver:POSV,desc:'BrowseStockItems1 + Product Insert Template → two POS outputs'},
 {id:'ch2',n:2,title:'OBORNE / CH2 DATABASE',ver:CH2V,desc:'ParagonCare pricelist + CR666a SOH → two CH2 outputs'},
 {id:'uhp',n:3,title:'UNIQUE / UHP DATABASE',ver:UHPV,desc:'Unique product export → two UHP outputs'},
 {id:'master',n:4,title:'COMBINED MASTER DATABASE',ver:MASTERV,desc:'Merge full POS, CH2 and Unique data (Python Step 3 V30.15) → full master + 98-column selected master; To-Order workbook when Availability is supplied. Suppliers link by barcode, SUB ID, brand and W/S with at least 2 match points.'}
];
const req=FILES.filter(x=>x[3]).map(x=>x[0]);
const STAGE_NAMES={pos:'POS Database',ch2:'Oborne / CH2 Database',uhp:'Unique / UHP Database',master:'Combined Master Database'};
function pretty(b){if(b<1024)return b+' B';if(b<1048576)return (b/1024).toFixed(1)+' KB';return (b/1048576).toFixed(1)+' MB'}
function stamp(){const p=new Intl.DateTimeFormat('en-GB',{timeZone:'Australia/Melbourne',day:'2-digit',month:'2-digit',year:'2-digit'}).formatToParts(new Date()),g=t=>p.find(x=>x.type===t)?.value||'';return `${g('day')}.${g('month')}.${g('year')}`}
function setGlobal(t,type='info'){let e=$('#globalStatus');e.className='status '+type;e.textContent=t}
function gpct(v){let p=$('#globalProgress'),b=$('#globalProgressBar');p.classList.toggle('hidden',v<=0);b.style.width=Math.max(0,Math.min(100,v))+'%'}
async function readSheets(file,opts={}){let ext=(file.name.split('.').pop()||'').toLowerCase(),wb;if(ext==='csv'||ext==='txt'){let text=await file.text();wb=XLSX.read(text,{type:'string',raw:true,cellDates:false})}else{let buf=await file.arrayBuffer();wb=XLSX.read(buf,{type:'array',raw:true,cellDates:false})}let active=Number(wb.Workbook?.WBView?.[0]?.activeTab)||0,out=wb.SheetNames.map(name=>({name,rows:XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:null,raw:true,blankrows:opts.blankrows!==false})}));out.active=Math.min(Math.max(0,active),Math.max(0,out.length-1));return out}
// Text-preserving read for the To-Order file (CSV values stay text, exactly like Python's csv module).
async function readTable(file){let ext=(file.name.split('.').pop()||'').toLowerCase();if(ext==='csv'||ext==='txt')return M.parseCsvText(await file.text());let sh=await readSheets(file);return (sh[sh.active]||sh[0])?.rows||[]}
function flatHeads(rows,max=12){let out=[];for(const r of (rows||[]).slice(0,max))for(const v of r||[])if(v!=null&&String(v).trim())out.push(String(v).trim().toUpperCase().replace(/[^A-Z0-9]+/g,' '));return out}
async function validateInputFile(id,file){try{let sheets=await readSheets(file,{blankrows:id!=='box'}),rows=sheets[0]?.rows||[],heads=flatHeads(rows,80),has=(...terms)=>terms.every(t=>heads.some(h=>h===t||h.includes(t)));if(!rows.length)return [false,'The file contains no readable rows.'];
 if(id==='stock'||id==='template'){if(!(has('MAIN ID')&&has('SUB ID')))return [false,'Expected POS fields MAIN_ID and SUB_ID were not found.'];return [true,'POS structure recognised.']}
 if(id==='brand'){let non=(rows||[]).filter(r=>(r||[]).filter(v=>v!=null&&String(v).trim()).length>=2);return non.length>=2?[true,'Brand mapping structure recognised.']:[false,'Expected a two-column brand mapping workbook.']}
 if(id==='discounts'){let d=M.detectDiscountRows(rows);return d.map.discount!==undefined?[true,`Discount matrix recognised; header row ${d.headerRow+1}.`]:[false,'Expected POS DISCOUNT% / OD_DISCOUNT % headings were not found.']}
 if(id==='ch2'){let q=C.parseSupplierSheets(sheets);return q?.rows?.length&&q?.headers?.some(h=>String(h).includes('ITEM_CODE'))?[true,`CH2 pricelist recognised (${q.rows.length.toLocaleString()} rows).`]:[false,'This does not look like a ParagonCare / CH2 pricelist.']}
 if(id==='soh'){let q=C.parseSoh(rows);return q?.data?.length?[true,`CR666a SOH structure recognised (${q.data.length.toLocaleString()} rows).`]:[false,'Expected CR666a stock-on-hand account/item/quantity structure was not found.']}
 if(id==='box'){let q=C.parseBoxSheets(sheets),hs=(q?.headers||[]).join(' ');return q?.rows?.length&&/HOW_MANY_IN_A_CT|CARTON|CTN/.test(hs)?[true,'Weight & Dimensions structure recognised.']:[false,'This is not a Weight & Dimensions workbook (carton quantity fields were not found).']}
 if(id==='uhp'){let q=U.parseUhpRows(rows);return q?.rows?.length&&q?.headers?.includes('UHP_BRAND')&&q?.headers?.some(h=>/BARCODE|APN/.test(h))?[true,`Unique / UHP structure recognised (${q.rows.length.toLocaleString()} rows).`]:[false,'Expected UHP Brand, Description, Size and APN/Barcode headings were not found.']}
 if(id==='availability'){let hdr=(rows[0]||[]).map(x=>String(x??'').trim().toUpperCase().replace(/[^A-Z0-9]+/g,' '));let plu=hdr.some(h=>h==='PLU SKU'||h==='PLU'||h==='SKU'||h==='ITEM CODE'),qty=hdr.some(h=>h==='QTY UNITS'||h==='QUANTITY'||h==='QTY'||h==='UNITS');return plu&&qty?[true,'To-Order / Availability structure recognised.']:[false,'Expected PLU / SKU and Qty / Units columns were not found.']}
 return [true,'File recognised.'];}catch(e){return [false,`Could not validate file: ${e.message}`]}}
async function acceptInputFile(id,file){if(!file)return false;let [ok,msg]=await validateInputFile(id,file);if(!ok){setGlobal(`${inputDef(id)?.[1]||id}: ${msg}`,'error');showInput(id,msg);return false}state.files[id]=file;state.validation=state.validation||{};state.validation[id]=msg;invalidate(id);renderInputNav();showInput(id,msg);updateBuildAll();return true}
async function brandMap(){let f=state.files.brand;if(!f)return new Map();let rows=(await readSheets(f))[0]?.rows||[],m=new Map();for(const r of rows.slice(1)){if(r.length>=2&&r[0]!=null&&r[1]!=null){let a=String(r[0]).replace(/[\x00-\x08\x0B\x0C\x0E-\x1F]/g,'').trim().toUpperCase(),b=String(r[1]).trim();if(a&&b)m.set(a,b)}}return m}
function blobUrl(blob){let u=URL.createObjectURL(blob);state.urls.push(u);return u}
function addOutput(stage,key,name,blob,meta){let old=state.outputs.get(key);if(old?.url)URL.revokeObjectURL(old.url);state.outputs.set(key,{stage,key,name,blob,meta,url:blobUrl(blob)});renderOutputs()}
function outputRows(arr){if(!arr.length)return '<div class="empty-output">No output files generated for this stage yet.</div>';return '<div class="output-list">'+arr.map(o=>`<div class="output-row"><div><code>${o.name}</code><span>${o.meta}</span></div><div class="output-actions"><a class="download-link" href="${o.url}" download="${o.name}">Download</a></div></div>`).join('')+'</div>'}
const OUTPUT_ORDER=['pos-main','pos-db','ch2-main','ch2-db','uhp-main','uhp-db','master-full','master-selected','master-order'];
function renderOutputs(){let host=$('#allOutputs'),arr=[...state.outputs.values()].sort((a,b)=>OUTPUT_ORDER.indexOf(a.key)-OUTPUT_ORDER.indexOf(b.key));if($('#outputCount')){$('#outputCount').textContent=`${arr.length} OUTPUT${arr.length===1?'':'S'}`;$('#outputCount').className='result-badge'+(arr.length?' ok':'')};if(host)host.innerHTML=arr.length?outputRows(arr):'<div class="empty-output">Build a stage to create its download files.</div>';for(const s of STAGES){let el=document.querySelector(`[data-stage-output="${s.id}"]`),rows=arr.filter(o=>o.stage===s.id);if(el)el.innerHTML=outputRows(rows)}}
function navState(id,status){}
function stageSet(id,status,msg){state.stageStatus[id]=status;let s=$(`#stage-${id}`);if(s){s.classList.remove('ready','running','done','error');s.classList.add(status==='waiting'?'ready':status);let b=s.querySelector('.small-badge');if(b){b.className='small-badge '+(status==='waiting'?'wait':status);b.textContent=status==='waiting'?'WAITING':status.toUpperCase()}let st=s.querySelector('.stage-status');if(st){st.textContent=msg;st.className='status stage-status '+({running:'running',done:'ok',error:'error'}[status]||'info')}}navState(id,status);updateMasterReadiness()}
function inputDef(id){return FILES.find(x=>x[0]===id)}
function renderInputSummary(){let h=$('#inputSummary');if(!h)return;let rc=$('#readyCount'),ready=0;let groups=['POS Inputs','Universal / Shared','Oborne / CH2 Inputs','Unique / UHP Inputs','Combined Master Inputs'];h.innerHTML=groups.map(g=>{let fs=FILES.filter(x=>x[5]===g),loaded=fs.filter(x=>state.files[x[0]]).length,reqs=fs.filter(x=>x[3]),missing=reqs.filter(x=>!state.files[x[0]]).length;return `<div class="summary-chip ${missing?'miss':((reqs.length||loaded)?'ok':'opt')}"><strong>${g}</strong><span>${loaded}/${fs.length} loaded${missing?` · ${missing} required missing`:(reqs.length?' · ready':' · optional')}</span></div>`}).join('');if(rc){ready=(state.files.stock&&state.files.template?1:0)+(state.files.ch2&&state.files.soh?1:0)+(state.files.uhp?1:0)+((state.files.stock&&state.files.template&&state.files.ch2&&state.files.soh&&state.files.uhp)?1:0);rc.textContent=`${ready} / 4 READY`;rc.className='result-badge '+(ready===4?'ok':ready?'ready':'')}}
function renderInputNav(){let host=$('#inputNav');if(!host)return;let groups=['POS Inputs','Universal / Shared','Oborne / CH2 Inputs','Unique / UHP Inputs','Combined Master Inputs'];host.innerHTML=groups.map(g=>`<div class="input-group"><div class="input-group-title">${g}</div>${FILES.filter(x=>x[5]===g).map(([id,title,desc,required])=>{let f=state.files[id],cls=`input-nav-item ${f?'loaded':'missing'} ${required?'required':''}`;return `<button type="button" class="${cls}" data-input="${id}" title="Click to open or drop the ${title} file directly here"><span class="input-dot">${f?'✓':required?'!':'○'}</span><span><strong>${title}</strong><small>${f?f.name:(required?'Required · drop here':'Optional · drop here')}</small></span><span class="input-state">${f?'LOADED':(required?'REQUIRED':'OPTIONAL')}</span></button>`}).join('')}</div>`).join('');host.querySelectorAll('[data-input]').forEach(b=>{let id=b.dataset.input;b.onclick=()=>showInput(id);b.ondragover=e=>{e.preventDefault();e.stopPropagation();b.classList.add('drag-target')};b.ondragenter=e=>{e.preventDefault();e.stopPropagation();b.classList.add('drag-target')};b.ondragleave=e=>{e.preventDefault();e.stopPropagation();b.classList.remove('drag-target')};b.ondrop=e=>{e.preventDefault();e.stopPropagation();b.classList.remove('drag-target');let file=e.dataTransfer?.files?.[0];if(!file)return;acceptInputFile(id,file)}});renderInputSummary()}
function showInput(id,validationMessage=''){let def=inputDef(id);if(!def)return;let [fid,title,desc,required,accept,group]=def,host=$('#inputWorkspace'),f=state.files[id];host.innerHTML=`<section class="panel input-workspace-card ${f?'is-loaded':required?'is-required':'is-optional'}"><div class="input-workspace-head"><div><div class="nav-separator" style="margin:0 0 6px">${group}</div><h2>${title}${required?' <span style="color:#b33">*</span>':''}</h2><p>${desc}</p></div><span class="small-badge ${f?'done':required?'required':'wait'}">${f?'LOADED':required?'REQUIRED':'OPTIONAL'}</span></div><div class="dropzone" tabindex="0"><div><strong>${f?'Replace file':'Drop file here'}</strong><small>or click to choose ${accept.replaceAll(',',' / ')}</small></div></div><input class="hidden" type="file" accept="${accept}"><div class="file-list">${f?`<div class="file-row"><span><strong>${f.name}</strong> · ${pretty(f.size)}</span><button type="button">Remove</button></div>`:''}</div><div class="input-meta"><div><strong>Used by</strong>${id==='brand'?'POS · CH2 · Unique':(['discounts','availability'].includes(id)?'Combined Master':group)}</div><div><strong>Session storage</strong>Browser memory only</div><div><strong>Status</strong>${f?(state.validation?.[id]||'Ready'):(validationMessage||'Not loaded')}</div></div></section>`;document.querySelectorAll('[data-input]').forEach(b=>b.classList.toggle('active',b.dataset.input===id));let d=host.querySelector('.dropzone'),i=host.querySelector('input'),rm=host.querySelector('.file-row button');const set=file=>{if(!file)return;acceptInputFile(id,file)};d.onclick=()=>i.click();d.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();i.click()}};i.onchange=()=>{set(i.files[0]);i.value=''};d.ondragover=e=>{e.preventDefault();d.classList.add('drag')};d.ondragleave=()=>d.classList.remove('drag');d.ondrop=e=>{e.preventDefault();d.classList.remove('drag');set(e.dataTransfer.files[0])};if(rm)rm.onclick=()=>{delete state.files[id];invalidate(id);renderInputNav();showInput(id);updateBuildAll()}}
function renderUploads(){renderInputNav();renderInputSummary()}
function invalidate(id){if(['stock','template','brand'].includes(id)){delete state.models.pos;deleteStageOutputs('pos');stageSet('pos','waiting','Ready when POS source files are available.')}if(['ch2','soh','brand','box'].includes(id)){delete state.models.ch2;deleteStageOutputs('ch2');stageSet('ch2','waiting','Ready when CH2 pricelist and SOH are available.')}if(['uhp','brand'].includes(id)){delete state.models.uhp;deleteStageOutputs('uhp');stageSet('uhp','waiting','Ready when the UHP export is available.')}if(['discounts','availability'].includes(id)){delete state.models.master;deleteStageOutputs('master');stageSet('master','waiting',`${id==='discounts'?'Discount':'Availability'} file changed. Rebuild Combined Master.`)}if(state.models.master){delete state.models.master;deleteStageOutputs('master');stageSet('master','waiting','Build Stages 1–3 first.')}updateMasterReadiness()}
function deleteStageOutputs(stage){for(const [k,o] of [...state.outputs])if(o.stage===stage){URL.revokeObjectURL(o.url);state.outputs.delete(k)}renderOutputs()}
function renderStageNav(){}
function masterExtra(){return `<div class="master-callout"><div><strong>Independent run</strong><span>If Stage 1–3 models are not built yet, Combined Master builds them automatically from the validated raw inputs already loaded in this session.</span></div><div><strong>Matching</strong><span>Each supplier row is scored on barcode (cleaned to the POS 13-digit form), SUB ID, brand and W/S (within 40%). A link needs 2 points including barcode or SUB ID; the best-scoring row wins. MATCH_BASIS in the full file shows why.</span></div><div><strong>Outputs</strong><span>Full merged master (downloads automatically) + 98-column selected master; To-Order workbook when Availability is loaded. Same columns, sort, formats and SUBTOTAL totals row as Python V30.15.</span></div></div><div class="input-readiness" id="masterReadiness"></div>`}
function renderStages(){for(const s of STAGES){let h=$(`#stage-${s.id}`);if(!h)continue;h.innerHTML=`<section class="panel stage-panel stage-view-card ready"><div class="stage-head"><div class="stage-title"><span class="stepnum">${s.n}</span><div><h2>${s.title} <small style="font-size:.6em;opacity:.65">${s.ver}</small></h2></div></div><span class="small-badge wait">WAITING</span></div><p class="stage-description">${s.desc}</p>${s.id==='master'?masterExtra():''}<div class="status info stage-status">Waiting for source files.</div><div class="stage-actions"><button class="btn primary stage-build" data-stage="${s.id}">Build ${s.title}</button></div><div class="stage-output-inline" data-stage-output="${s.id}"></div></section>`}document.querySelectorAll('.stage-build').forEach(b=>b.onclick=()=>buildStage(b.dataset.stage));updateMasterReadiness()}
function activateView(view){}
function bindNavigation(){}
function updateMasterReadiness(){let h=$('#masterReadiness');if(!h)return;h.innerHTML=[['pos','POS',['stock','template']],['ch2','CH2',['ch2','soh']],['uhp','Unique',['uhp']]].map(([id,label,ids])=>{let built=!!state.models[id],ok=built||ids.every(k=>state.files[k]);return `<span class="ready-chip ${ok?'ok':'missing'}">${label} · ${built?'built':ok?'inputs ready':'files missing'}</span>`}).join('')}
function stageMissing(id){let need={pos:['stock','template'],ch2:['ch2','soh'],uhp:['uhp']}[id]||req;return need.filter(k=>!state.files[k]).map(k=>inputDef(k)?.[1]||k)}
function stagePrereqs(id){if(id==='pos')return !!(state.files.stock&&state.files.template);if(id==='ch2')return !!(state.files.ch2&&state.files.soh);if(id==='uhp')return !!state.files.uhp;return !!(state.files.stock&&state.files.template&&state.files.ch2&&state.files.soh&&state.files.uhp)}
function refreshStageReadiness(){for(const st of STAGES){if(['running','done','error'].includes(state.stageStatus[st.id]))continue;let ready=stagePrereqs(st.id),el=document.querySelector(`[data-stage-nav="${st.id}"] .nav-state`);if(el){el.className='nav-state '+(ready?'ready':'');el.textContent=ready?'READY':'WAIT'}let card=$(`#stage-${st.id}`);if(card){let badge=card.querySelector('.small-badge'),msg=card.querySelector('.stage-status');if(badge){badge.className='small-badge '+(ready?'ready':'wait');badge.textContent=ready?'READY':'WAITING'}if(msg){let miss=stageMissing(st.id);msg.className='status stage-status '+(ready?'ready':'missing');msg.textContent=ready?'Validated inputs are ready. This stage can run independently.':'Missing: '+miss.join(', ')};let run=card.querySelector('.stage-build');if(run)run.disabled=!ready}}}
function updateBuildAll(keepStatus){let ok=req.every(k=>state.files[k]);$('#buildAllBtn').disabled=!ok;if(keepStatus){}else if(ok)setGlobal('All required raw files are validated. Build All will create POS, CH2, Unique and Combined Master without re-uploading.','ready');else setGlobal('Missing: '+req.filter(k=>!state.files[k]).map(k=>inputDef(k)?.[1]||k).join(', ')+'.','missing');refreshStageReadiness();updateMasterReadiness()}
// ---------- workbook helpers ----------
function addBasic(ws,headers,rows,text=new Set()){ws.addRow(headers);ws.getRow(1).font={bold:true};rows.forEach(r=>ws.addRow(r));ws.autoFilter={from:{row:1,column:1},to:{row:Math.max(1,ws.rowCount),column:headers.length}};ws.views=[{state:'frozen',ySplit:1}];ws.eachRow({includeEmpty:true},(r,n)=>{r.height=15;r.eachCell({includeEmpty:true},c=>c.alignment={wrapText:false,shrinkToFit:false,vertical:n===1?'middle':'top'})});headers.forEach((h,i)=>{if(text.has(h))ws.getColumn(i+1).eachCell({includeEmpty:true},c=>c.numFmt='@')})}
async function makeBasic(sheet,headers,rows,text){let wb=new ExcelJS.Workbook(),ws=wb.addWorksheet(sheet);addBasic(ws,headers,rows,text);return new Blob([await wb.xlsx.writeBuffer()],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}
async function verifyBasic(blob,sheet,headers,rows){let wb=XLSX.read(await blob.arrayBuffer(),{type:'array',raw:true}),ws=wb.Sheets[sheet];if(!ws)throw new Error(sheet+': worksheet missing');let a=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:true,blankrows:true});if(a.length!==rows.length+1)throw new Error(`${sheet}: expected ${rows.length} rows, got ${a.length-1}`);if((a[0]||[]).length!==headers.length||headers.some((h,i)=>String(a[0][i]??'')!==h))throw new Error(sheet+': output headers differ from required layout')}
// ---------- POS ----------
const POS_BASE=['MAIN_ID','PLU','SUB_ID','BRAND','DESCR','POS_DESC','DISSNO','PROD_GRP','SUPPLIER','LOYALTY_SCHEME','UNITS','MIN_ORDER_QTY','WSP_EXCGST','LAST_PRICE','GST_TAX_PC','RRP_INCGST','PR_1_PC','PR_2_PC','PR_3_PC','PR_4_PC','PR_5_PC','PR_6_PC','PR_7_PC','PR_8_PC','PR_9_PC','RET_PRICE','PHARM_PROD','SCALES','ITEMSIZE','PACKAGING','SOH'];
const POS_STD=['POS_INDEX','POS_MASTER_BRAND','POS_MASTER_BARCODE','POS_MAIN_ID','POS_PLU','POS_SUB_ID','POS_BRAND','POS_DESCR','POS_POS_DESC','POS_DISSNO','POS_PROD_GRP','POS_SUPPLIER','POS_LOYALTY_SCHEME','POS_UNITS','POS_MIN_ORDER_QTY','POS_WSP_EXCGST','POS_LAST_PRICE','POS_GST_TAX_PC','POS_RRP_INCGST','POS_PR_1_PC','POS_PR_2_PC','POS_PR_3_PC','POS_PR_4_PC','POS_PR_5_PC','POS_PR_6_PC','POS_PR_7_PC','POS_PR_8_PC','POS_PR_9_PC','POS_RET_PRICE','POS_PHARM_PROD','POS_SCALES','POS_ITEMSIZE','POS_PACKAGING','POS_SOH'];
const POS_DB=['INDEX','POS_MASTER_BRAND','POS_MASTER_BARCODE','POS_PLU','POS_SUB_ID','POS_BRAND','POS_DESCR','POS_POS_DESC','POS_DISSNO','POS_PROD_GRP','POS_SUPPLIER','POS_LOYALTY_SCHEME','POS_UNITS','POS_MIN_ORDER_QTY','POS_WSP_EXCGST','POS_LAST_PRICE','POS_GST_TAX_PC','POS_RRP_INCGST','POS_PR_1_PC','POS_PR_2_PC','POS_PR_3_PC','POS_PR_4_PC','POS_PR_5_PC','POS_PR_6_PC','POS_PR_7_PC','POS_PR_8_PC','POS_PR_9_PC','POS_RET_PRICE','POS_PHARM_PROD','POS_SCALES','POS_ITEMSIZE','POS_PACKAGING','POS_SOH','STATUS'];
function cleanCtl(v){return String(v??'').replace(/_x00(?:0[0-8BCEF]|1[0-9A-F])_/gi,'').replace(/[\x00-\x08\x0B\x0C\x0E-\x1F]/g,'')}
function posVal(v,h){if(v==null)return'';if(['MAIN_ID','SUB_ID','BRAND','DESCR','POS_DESC','PACKAGING'].includes(h))return cleanCtl(v).trim().toUpperCase().replace(/'/g,'');if(['WSP_EXCGST','LAST_PRICE','RRP_INCGST','LAST_DPRICE'].includes(h)){let n=Number(v);return Number.isFinite(n)?n:0}let s=cleanCtl(v).trim();if(s==='')return 0;let n=Number(s);return Number.isFinite(n)?Math.trunc(n):s.toUpperCase()}
async function posRead(f){let sh=(await readSheets(f))[0],a=sh?.rows||[];if(!a.length)return{headers:[],rows:[]};let headers=(a[0]||[]).filter(x=>x!=null&&String(x).trim()).map(x=>String(x).trim().toUpperCase()),rows=a.slice(1).map(r=>{let o={};headers.forEach((h,i)=>o[h]=posVal(r[i],h));return o});return{headers,rows}}
function normPosBarcode(v){let d=String(v??'').replace(/\D/g,'');return d?d.padStart(13,'0'):''}
function cmp(a,b){a=String(a??'').trim().toUpperCase();b=String(b??'').trim().toUpperCase();return a<b?-1:a>b?1:0}
async function buildPos(){if(!state.files.stock||!state.files.template)throw new Error('POS requires BrowseStockItems1 and Product Insert Template.');stageSet('pos','running','Reading and merging POS source files…');let [s,t,bm]=await Promise.all([posRead(state.files.stock),posRead(state.files.template),brandMap()]),look=new Map(t.rows.map(r=>[`${r.MAIN_ID??''}\0${r.SUB_ID??''}`,r])),rows=[];s.rows.forEach((sr,i)=>{let tr=look.get(`${sr.MAIN_ID??''}\0${sr.SUB_ID??''}`)||{},o={POS_INDEX:i+1};for(const c of POS_BASE)o['POS_'+c]=(sr[c]!==''&&sr[c]!=null)?sr[c]:tr[c];let br=String(o.POS_BRAND??''),mb=bm.get(br.trim().toUpperCase())??br;o.POS_MASTER_BRAND=mb;o.POS_MASTER_BARCODE=normPosBarcode(o.POS_MAIN_ID);rows.push(o)});let db=rows.slice().sort((a,b)=>cmp(a.POS_MASTER_BRAND,b.POS_MASTER_BRAND)||cmp(a.POS_BRAND,b.POS_BRAND)||cmp(a.POS_DESCR,b.POS_DESCR)||cmp(a.POS_MASTER_BARCODE,b.POS_MASTER_BARCODE)).map((r,i)=>({...r,INDEX:i+1,STATUS:''}));let txt=new Set(['POS_MASTER_BARCODE','POS_MAIN_ID','POS_PLU','POS_SUB_ID','POS_BRAND','POS_DESCR','POS_POS_DESC','POS_PACKAGING']),dtxt=new Set(['POS_MASTER_BARCODE','POS_PLU','POS_SUB_ID','POS_BRAND','POS_DESCR','POS_POS_DESC','POS_PACKAGING','STATUS']);let [main,pdb]=await Promise.all([makeBasic('Clean_Merged_POS_Data',POS_STD,rows.map(r=>POS_STD.map(h=>r[h]??'')),txt),makeBasic('POS_DB_Data',POS_DB,db.map(r=>POS_DB.map(h=>r[h]??'')),dtxt)]);await verifyBasic(main,'Clean_Merged_POS_Data',POS_STD,rows);await verifyBasic(pdb,'POS_DB_Data',POS_DB,db);let d=stamp();addOutput('pos','pos-main',`clean_merged_pos_data_${d}.xlsx`,main,`${rows.length.toLocaleString()} rows · full working file`);addOutput('pos','pos-db',`clean_merged_pos_data_pos_db_${d}.xlsx`,pdb,`${db.length.toLocaleString()} rows · POS DB layout`);state.models.pos={headers:POS_STD,rows:rows.map(r=>POS_STD.map(h=>r[h]??''))};stageSet('pos','done',`Complete — ${rows.length.toLocaleString()} POS rows · 2 / 2 outputs ready.`)}
// ---------- CH2 ----------
async function buildCh2(){if(!state.files.ch2||!state.files.soh)throw new Error('CH2 requires ParagonCare / CH2 Pricelist and CR666a Stock On Hand.');stageSet('ch2','running','Reading CH2 pricelist and current SOH…');let [sup,soh,bm]=await Promise.all([readSheets(state.files.ch2),readSheets(state.files.soh),brandMap()]),p=C.parseSupplierSheets(sup),pr=C.processSupplier(p.headers,p.rows,bm),en=C.addEnhanced(pr.headers,pr.rows),sp=C.parseSoh(soh[0]?.rows||[]),lk=C.buildSohLookup(sp.data),mg=C.augmentSoh(en.headers,en.rows,lk.lookup);if(state.files.box){let bp=C.parseBoxSheets(await readSheets(state.files.box,{blankrows:false})),bx=C.mergeBox(mg.headers,mg.rows,bp.headers,bp.rows);mg={headers:bx.headers,rows:bx.rows}}let pos=C.buildSupplierImport(mg.headers,mg.rows),mt=new Set(mg.headers.filter(h=>h.includes('BARCODE'))),pt=new Set(['SUP BARCODE','SUP SUB ID']);let [main,pdb]=await Promise.all([makeBasic('Supplier_Data',mg.headers,mg.rows,mt),makeBasic('IN_SUPPLIER_UPDATE',C.SUPPLIER_IMPORT_HEADERS,pos,pt)]);await verifyBasic(main,'Supplier_Data',mg.headers,mg.rows);await verifyBasic(pdb,'IN_SUPPLIER_UPDATE',C.SUPPLIER_IMPORT_HEADERS,pos);let d=stamp();addOutput('ch2','ch2-main',`clean_ch2_data_${d}.xlsx`,main,`${mg.rows.length.toLocaleString()} rows · full working file`);addOutput('ch2','ch2-db',`clean_ch2_data_pos_db_${d}.xlsx`,pdb,`${pos.length.toLocaleString()} rows · supplier import layout`);state.models.ch2={headers:mg.headers,rows:mg.rows};stageSet('ch2','done',`Complete — ${mg.rows.length.toLocaleString()} CH2 rows · 2 / 2 outputs ready.`)}
// ---------- UHP ----------
async function buildUhp(){if(!state.files.uhp)throw new Error('Unique / UHP requires a UHP product export.');stageSet('uhp','running','Reading and processing Unique / UHP export…');let [s,bm]=await Promise.all([readSheets(state.files.uhp),brandMap()]),p=U.parseUhpRows(s[0]?.rows||[]),pr=U.processUhp(p.headers,p.rows,bm),pos=U.buildSupplierImport(pr.headers,pr.rows),mt=new Set(pr.headers.filter(h=>['BARCODE','APN','EAN','UPC'].some(k=>h.includes(k)))),pt=new Set(['SUP BARCODE','SUP SUB ID']);let [main,pdb]=await Promise.all([makeBasic('UHP_Data',pr.headers,pr.rows,mt),makeBasic('IN_SUPPLIER_UPDATE',U.SUPPLIER_IMPORT_HEADERS,pos,pt)]);await verifyBasic(main,'UHP_Data',pr.headers,pr.rows);await verifyBasic(pdb,'IN_SUPPLIER_UPDATE',U.SUPPLIER_IMPORT_HEADERS,pos);let d=stamp();addOutput('uhp','uhp-main',`clean_uhp_data_${d}.xlsx`,main,`${pr.rows.length.toLocaleString()} rows · full working file`);addOutput('uhp','uhp-db',`clean_uhp_data_pos_db_${d}.xlsx`,pdb,`${pos.length.toLocaleString()} rows · supplier import layout`);state.models.uhp={headers:pr.headers,rows:pr.rows};stageSet('uhp','done',`Complete — ${pr.rows.length.toLocaleString()} Unique / UHP rows · 2 / 2 outputs ready.`)}
// ---------- MASTER (Python Step 3 V30.15 via MasterCore v2) ----------
async function verifyMasterWorkbook(blob,sheet,headers,records,kind){
 // Re-open the written workbook and double check headers, row count, the totals row and sample cells.
 let wb=XLSX.read(await blob.arrayBuffer(),{type:'array',raw:true}),ws=wb.Sheets[sheet];if(!ws)throw new Error(`${sheet}: worksheet missing`);
 let a=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:true,blankrows:true}),hdr=(a[0]||[]).map(x=>String(x));
 if(hdr.length!==headers.length||headers.some((h,i)=>hdr[i]!==h))throw new Error(`${sheet}: header row differs from the required layout`);
 if(a.length!==records.length+2)throw new Error(`${sheet}: expected ${records.length} data rows + totals, found ${a.length-1}`);
 let tot=a[a.length-1];if(kind!=='order'&&String(tot[0])!=='📊 FILTERED TOTALS:')throw new Error(`${sheet}: totals row missing`);
 let key=headers.indexOf('MASTER_BARCODE'),pi=headers.indexOf(kind==='order'?'PLU / SKU':'POS_INDEX'),step=Math.max(1,Math.floor(records.length/200));
 for(let r=0;r<records.length;r+=step){let rec=records[r],row=a[r+1];if(key>=0&&String(row[key]??'')!==String(rec.MASTER_BARCODE??''))throw new Error(`${sheet}: row ${r+2} MASTER_BARCODE mismatch`);let pk=kind==='order'?'AV_PLU_SKU':'POS_INDEX';if(pi>=0&&String(row[pi]??'')!==String(rec[pk]??''))throw new Error(`${sheet}: row ${r+2} ${pk} mismatch`)}
}
function downloadBlob(blob,name){let a=document.createElement('a');a.href=blobUrl(blob);a.download=name;a.rel='noopener';document.body.appendChild(a);a.click();setTimeout(()=>a.remove(),1000)}
async function buildMaster(){if(!state.models.pos){if(!state.files.stock||!state.files.template)throw new Error('Combined Master needs POS inputs or a completed POS stage.');await buildPos()}if(!state.models.ch2){if(!state.files.ch2||!state.files.soh)throw new Error('Combined Master needs CH2 inputs or a completed CH2 stage.');await buildCh2()}if(!state.models.uhp){if(!state.files.uhp)throw new Error('Combined Master needs the Unique / UHP input or a completed Unique stage.');await buildUhp()}
 stageSet('master','running','Reading current CR666a SOH, discounts and To-Order data…');
 let [sohSheets,bm,discRows,avRows]=await Promise.all([readSheets(state.files.soh),brandMap(),state.files.discounts?readSheets(state.files.discounts).then(sh=>(sh[sh.active]||sh[0])?.rows||[]):null,state.files.availability?readTable(state.files.availability):null]);
 stageSet('master','running','Matching POS, CH2 and Unique (barcode → SUB ID → brand → W/S, minimum 2 points) and pricing…');await new Promise(r=>setTimeout(r,30));
 let res=M.buildMaster({pos:state.models.pos,ch2:state.models.ch2,uhp:state.models.uhp,sohSheets,discountRows:discRows,availabilityRows:avRows,brandMap:bm});
 let d=stamp(),fullName=`merged_alligned_pos_supplier_uhp_full_${d}.xlsx`,selName=`merged_alligned_pos_supplier_uhp_selected_columns_${d}.xlsx`,ordName=`to_order_with_av_supplier_codes_${d}.xlsx`,n=res.records.length;
 const prog=(label)=>(sheet,r)=>stageSet('master','running',`Writing ${label} — ${r.toLocaleString()} / ${(n+2).toLocaleString()} rows…`);
 let fullBlob=await M.writeMasterWorkbook('full',res,{onProgress:prog('full merged dataset')});await verifyMasterWorkbook(fullBlob,'Full_Data',res.outHeaders,res.records,'full');
 addOutput('master','master-full',fullName,fullBlob,`${n.toLocaleString()} rows · ${res.outHeaders.length} columns · full merged dataset`);
 let selBlob=await M.writeMasterWorkbook('selected',res,{onProgress:prog('selected master')});await verifyMasterWorkbook(selBlob,'Selected_Data',res.selectedHeaders,res.records,'selected');
 addOutput('master','master-selected',selName,selBlob,`${n.toLocaleString()} rows · ${res.selectedHeaders.length} columns · styled selected master${state.files.discounts?' · discounts applied':''}`);
 let orderCount=res.order.records.length;
 if(orderCount){let ordBlob=await M.writeMasterWorkbook('order',res);await verifyMasterWorkbook(ordBlob,'To_Order',res.order.display,res.order.records,'order');addOutput('master','master-order',ordName,ordBlob,`${orderCount.toLocaleString()} rows · availability / fulfilment order file`)}
 state.models.master={...res,fullHeaders:res.outHeaders};
 let st=res.stats,ch2Linked=st.barcode_ch2+st.brand_subid_ch2+st.code_ch2+st.subid_ws_ch2,uhpLinked=st.barcode_uhp+st.brand_subid_uhp+st.code_uhp+st.subid_ws_uhp,rej=st.rejected_ch2+st.rejected_uhp;
 let fulfil=state.files.availability?` · order check ${res.validation.integrity}%`:'';
 downloadBlob(fullBlob,fullName);
 stageSet('master','done',`Complete — ${n.toLocaleString()} master records · POS→CH2 ${ch2Linked.toLocaleString()} · POS→Unique ${uhpLinked.toLocaleString()} · CH2 excluded ${st.excluded_ch2.toLocaleString()} · Unique excluded ${st.excluded_uhp.toLocaleString()}${rej?` · ${rej} single-point barcode link${rej===1?'':'s'} held back for review (see MATCH_BASIS)`:''}${fulfil} · ${orderCount?3:2} outputs verified · full file downloaded.`)}
async function buildStage(id){let keep=false;document.querySelectorAll('.stage-build').forEach(b=>b.disabled=true);try{if(id==='pos')await buildPos();else if(id==='ch2')await buildCh2();else if(id==='uhp')await buildUhp();else await buildMaster();setGlobal(`${STAGE_NAMES[id]} complete — ${state.outputs.size} output file${state.outputs.size===1?'':'s'} ready below${id==='master'?'; the full merged dataset was downloaded automatically':''}.`,'success');keep=true}catch(e){console.error(e);stageSet(id,'error','Error: '+e.message);setGlobal(`${STAGE_NAMES[id]} failed: ${e.message}`,'error');keep=true}finally{document.querySelectorAll('.stage-build').forEach(b=>b.disabled=false);updateBuildAll(keep)}}
async function buildAll(){let b=$('#buildAllBtn');b.disabled=true;document.querySelectorAll('.stage-build').forEach(x=>x.disabled=true);try{gpct(5);setGlobal('Stage 1 of 4 — building POS database…','running');await buildPos();gpct(28);setGlobal('Stage 2 of 4 — building Oborne / CH2 database…','running');await buildCh2();gpct(53);setGlobal('Stage 3 of 4 — building Unique / UHP database…','running');await buildUhp();gpct(76);setGlobal('Stage 4 of 4 — building Combined Master from in-memory outputs…','running');await buildMaster();gpct(100);setGlobal(`Complete — ${state.outputs.size} output files are ready below; the full merged dataset was downloaded automatically. No re-uploading was used between stages.`,'success');setTimeout(()=>gpct(0),700)}catch(e){console.error(e);gpct(0);setGlobal('Build All stopped: '+e.message,'error')}finally{document.querySelectorAll('.stage-build').forEach(x=>x.disabled=false);updateBuildAll(true)}}
renderUploads();renderStageNav();renderStages();renderOutputs();bindNavigation();updateBuildAll();$('#buildAllBtn').onclick=buildAll;$('#clearAllBtn').onclick=()=>{for(const u of state.urls)URL.revokeObjectURL(u);location.reload()};
})();
