(function(global){
'use strict';
const SUPPLIER_IMPORT_HEADERS=['INDEX','POS SUPPLIER NAME','POS SUPPLIER NUMBER','SUP BARCODE','SUP BRAND','SUP SUB ID','SUP PRODUCT','SUP UNITS IN PACK','SUP MIN ORDER WS','SUP WS EXGST','SUP RRP INC GST','SUP GST','SUP STOCK IN','SUP DISCOUNT PRICE','POS MEMBER','STATUS'];
const SUPPLIER_IMPORT_MAPPING=['UHP_INDEX','UNIQUE',188,'UHP_MASTER_BARCODE','UHP_MASTER_BRAND','UHP_STOCKCODE','UHP_DESCRIPTION','UHP_MOQ','UHP_CTN_QTY','UHP_WS_EX_GST','UHP_RRP','UHP_GST','','','',''];
function cleanExcelText(v){if(v===null||v===undefined)return '';return String(v).replace(/_x00(?:0[0-8BCEF]|1[0-9A-F])_/gi,'').replace(/[\x00-\x08\x0B\x0C\x0E-\x1F]/g,'');}
function cleanHeaderName(name,prefix='UHP_'){if(name===null||name===undefined||!String(name).trim())return '';let s=cleanExcelText(name).trim().replace(/[\r\n]+/g,' ');s=s.replace(/\//g,'').replace(/\./g,'_').replace(/[^\w\s]/g,'').replace(/[\s_]+/g,'_').replace(/^_+|_+$/g,'').toUpperCase();return prefix+s;}
function isHeaderRow(row){if(!row||!row.length)return false;const vals=row.map(v=>v==null?'':String(v).toLowerCase().trim());if(vals.filter(Boolean).length<4)return false;const n=vals.map(v=>v.replace(/[^a-z0-9]+/g,' ').trim());const hasBrand=n.some(v=>v==='brand'),hasDescription=n.some(v=>v==='description'),hasSize=n.some(v=>v==='size'),hasBarcode=n.some(v=>v==='barcode'||(v.split(' ').includes('apn')&&v.split(' ').includes('barcode')));return hasBrand&&hasDescription&&hasSize&&hasBarcode;}
function parseUhpRows(allRows){if(!allRows||!allRows.length)throw new Error('No data found in UHP file');let hi=-1;for(let i=0;i<Math.min(50,allRows.length);i++){if(isHeaderRow(allRows[i])){hi=i;break}}if(hi<0)throw new Error('Could not detect header row');const raw=allRows[hi]||[],data=allRows.slice(hi+1);let start=0;for(let i=0;i<raw.length;i++){if(raw[i]!=null&&String(raw[i]).trim()){start=i;break}}const headers=[];for(let i=start;i<raw.length;i++){const h=cleanHeaderName(raw[i]);if(h)headers.push(h)}const rows=[];for(const row0 of data){const row=(row0||[]).slice(start,start+headers.length);while(row.length<headers.length)row.push(null);if(row.some(c=>c!=null&&String(c).trim()))rows.push(row)}return {headers,rows,headerIdx:hi};}
function normalizeBarcode(v){if(v===null||v===undefined)return '';let d=String(v).replace(/\D/g,'');if(!d||d.length>14)return '';if(d.length===14)d=d.slice(1);if(d.length<13)d=d.padStart(13,'0');return d.length===13?d:'';}
function pyStr(v){if(v===null)return 'None';if(v===undefined)return '';return String(v);} function applyBrand(name,map){if(!name||!map||!map.size)return name;return map.get(String(name).trim().toUpperCase())??name;}
function processUhp(headers,dataRows,brandMap){const bi=headers.indexOf('UHP_BRAND'),di=headers.indexOf('UHP_DESCRIPTION'),si=headers.indexOf('UHP_SIZE'),bci=headers.findIndex(h=>h.includes('APN')||h.includes('BARCODE'));const outputHeaders=['UHP_INDEX','UHP_MASTER_BRAND','UHP_MASTER_BARCODE',...headers];const upper=new Set(['UHP_INDEX','UHP_MASTER_BRAND','UHP_BRAND','UHP_DESCRIPTION','UHP_ADDITIONALDESCRIPTION','UHP_SIZE','UHP_GST']);let subs=0,rowIndex=0;const rows=[];for(const source of dataRows){if(!source.some(c=>c!=null&&String(c).trim()))continue;rowIndex++;const row=source.slice();while(row.length<headers.length)row.push(null);const original=bi>=0?pyStr(row[bi]).trim():'';const master=applyBrand(original,brandMap);if(master!==original&&original)subs++;const masterBarcode=bci>=0?normalizeBarcode(row[bci]):'';const current=di>=0?pyStr(row[di]).trim():'',brand=bi>=0?pyStr(row[bi]).trim():'',size=si>=0?pyStr(row[si]).trim():'';if(di>=0)row[di]=[brand,current,size].filter(Boolean).join(' ').trim();let final=[rowIndex,master,masterBarcode,...row];final=final.map((cell,i)=>{if(upper.has(outputHeaders[i])&&typeof cell==='string')return cell.toUpperCase();return cell;});rows.push(final)}return {headers:outputHeaders,rows,brandSubstitutions:subs};}
function get(headers,row,name,def=''){const i=headers.indexOf(name);if(i<0||i>=row.length)return def;const v=row[i];return v==null?'':v;}
function buildSupplierImport(headers,rows){return rows.map(row=>SUPPLIER_IMPORT_MAPPING.map(m=>{if(m===''||m===null)return '';if(typeof m==='number')return m;if(headers.includes(m))return get(headers,row,m);return m;}));}
const api={SUPPLIER_IMPORT_HEADERS,cleanExcelText,cleanHeaderName,isHeaderRow,parseUhpRows,normalizeBarcode,processUhp,buildSupplierImport};
if(typeof module!=='undefined'&&module.exports)module.exports=api;global.UHPCore=api;
})(typeof window!=='undefined'?window:globalThis);
