(function(g){'use strict';
const SELECTED=[
'MASTER_BRAND','MASTER_BARCODE','MASTER_POS_PLU','MATCH_STATUS','POS_INDEX','CH2_INDEX','UHP_INDEX','AV_INDEX','POS_MASTER_BRAND','POS_MASTER_BARCODE','POS_MAIN_ID','POS_PLU','POS_SUB_ID','POS_BRAND','POS_DESCR','POS_POS_DESC','POS_DISSNO','POS_PROD_GRP','POS_SUPPLIER','POS_LOYALTY_SCHEME','POS_UNITS','POS_MIN_ORDER_QTY','POS_WSP_EXCGST','POS_LAST_PRICE','POS_GST_TAX_PC','POS_RRP_INCGST','POS_PR_1_PC','POS_PR_2_PC','POS_PR_3_PC','POS_PR_4_PC','POS_PR_5_PC','POS_PR_6_PC','POS_PR_7_PC','POS_PR_8_PC','POS_PR_9_PC','POS_RET_PRICE','POS_PHARM_PROD','POS_SCALES','POS_ITEMSIZE','POS_PACKAGING','POS_SOH','CH2_MASTER_BRAND','CH2_MASTER_BARCODE','CH2_VENDOR_NAME','CH2_BRAND','CH2_PGC_ITEM_CODE','CH2_LONG_DESCRIPTION_ENHANCED','CH2_WHOLESALE_EX_GST','CH2_RRP_INC_GST','CH2_GST_YN','CH2_NOTES','BOX_HOW_MANY_IN_A_CT','UHP_MASTER_BRAND','UHP_MASTER_BARCODE','UHP_STOCKCODE','UHP_BRAND','UHP_DESCRIPTION','UHP_WS_EX_GST','UHP_GST','UHP_RRP','UHP_MOQ','UHP_UNIT_WS_EX_GST','UHP_CTN_QTY','UHP_CTN_BARCODE','SOH_310_MELBOURNE','SOH_315_HOBART','SOH_330_SYDNEY','SOH_335_NEWCASTLE','SOH_340_ADELAIDE','SOH_350_BRISBANE','SOH_353_BRISBANE_4PL','SOH_355_TOWNSVILLE','SOH_370_PERTH','CURRENT_WSP','NEW_WSP','WSP_CHANGE_PCT','WSP_CHANGE_$','CURRENT_LAST_PRICE','NEW_LAST_PRICE','CHANGE_PCT_LAST_PRICE','WSP_CHANGE_$_LAST_PRICE','DISCOUNT_TYPE','DISCOUNT_PCT','CURRENT_RRP','NEW_RRP','HAS_GST','AV_BRAND','AV_BARCODE','AV_SUPPLIER_NUMBER','AV_PLU_SKU','AV_QTY_UNITS','OF_MELB','OF_NEWCASTLE','OF_ADELAIDE','OF_SYDNEY','OF_BRISBANE','OF_PERTH','OF_SHORTFALL'];
const SOH=['SOH_310_MELBOURNE','SOH_315_HOBART','SOH_330_SYDNEY','SOH_335_NEWCASTLE','SOH_340_ADELAIDE','SOH_350_BRISBANE','SOH_353_BRISBANE_4PL','SOH_355_TOWNSVILLE','SOH_370_PERTH'];
const keyMap={pos:{brand:['POS_MASTER_BRAND','POS_BRAND'],barcode:['POS_MASTER_BARCODE','POS_BARCODE'],code:['POS_SUB_ID','POS_PLU','POS_MAIN_ID'],plu:['POS_PLU'],sub_id:['POS_SUB_ID'],wsp:['POS_WSP_EXCGST','POS_WSP'],last_price:['POS_LAST_PRICE'],rrp:['POS_RRP_INCGST','POS_RRP'],supplier_id:['POS_SUPPLIER'],description:['POS_DESCR','POS_DESCRIPTION'],gst:['POS_GST_TAX_PC']},supplier:{brand:['CH2_MASTER_BRAND','CH2_BRAND'],barcode:['CH2_MASTER_BARCODE','CH2_BAR_CODE','CH2_BARCODE'],code:['CH2_PGC_ITEM_CODE','CH2_ITEM_CODE'],wsp:['CH2_WHOLESALE_EX_GST','CH2_WHOLESALE','CH2_WSP'],rrp:['CH2_RRP_INC_GST','CH2_RRP'],gst:['CH2_GST_YN','CH2_GST']},uhp:{brand:['UHP_MASTER_BRAND','UHP_BRAND'],barcode:['UHP_MASTER_BARCODE','UHP_APN_BARCODE','UHP_BARCODE'],code:['UHP_STOCKCODE','UHP_CODE'],description:['UHP_DESCRIPTION','UHP_DESCR'],size:['UHP_SIZE'],wsp:['UHP_WS_EX_GST','UHP_WSP'],rrp:['UHP_RRP'],gst:['UHP_GST']}};
function findCols(headers,type){let out={};let up=headers.map(x=>String(x||'').trim().toUpperCase()); for(const [k,arr] of Object.entries(keyMap[type])) for(const p of arr){let i=up.indexOf(p.toUpperCase());if(i>=0){out[k]=headers[i];break}} return out}
function cleanBarcode(v){if(v===null||v===undefined)return'';let d=String(v).trim().replace(/["']/g,'').replace(/\D/g,'');if(!d||d.length>14)return'';if(d.length===14)d=d.slice(1);else if(d.length<13)d=d.padStart(13,'0');return d.length===13?d:''}
function cleanCode(v){if(v===null||v===undefined)return'';return String(v).trim().toUpperCase().replace(/[^A-Z0-9]/g,'')}
function cleanBrand(v){return v===null||v===undefined?'':String(v).trim().toUpperCase()}
function brandsMatch(a,b){if(!a||!b)return false;a=cleanBrand(a);b=cleanBrand(b);if(a===b||a.includes(b)||b.includes(a))return true;let x=a.replace(/[^A-Z0-9]/g,''),y=b.replace(/[^A-Z0-9]/g,'');return x===y||x.includes(y)||y.includes(x)}
function num(v){if(v===null||v===undefined||String(v).trim()==='')return null;let n=Number(v);return Number.isFinite(n)?n:null}
function int(v){let n=num(v);return n===null?null:Math.trunc(n)}
function cleanLookup(v){if(v===null||v===undefined)return'';if(typeof v==='number'&&Number.isInteger(v))return String(v);let s=String(v).trim().replace(/["']/g,'');if(/^[-+]?\d+\.0+$/.test(s))return String(Math.trunc(Number(s)));return s}
function pct(v){if(v===null||v===undefined||String(v).trim()==='')return null;let s=String(v).trim(),n;if(s.includes('%'))n=Number(s.replace('%','').trim())/100;else{n=Number(s);if(!Number.isFinite(n))return null;n=Math.abs(n)<=1?n:n/100}return Number.isFinite(n)?n:null}
function normHead(v){return String(v??'').trim().toUpperCase().replace(/[^A-Z0-9]+/g,' ')}
const DHEAD={supplier:['POS SUPPLIER NUMBER','POS_SUPPLIER_NUMBER','OD_SUPPLIER_DISCOUNT','OD_SUPPLIER DISCOUNT'],brand:['POS MASTER BRAND','POS_MASTER_BRAND','OD_MASTER_BRAND','OD_MASTER BRAND','OD_BRAND'],prefix:['POS BRAND PREFIX','POS_BRAND_PREFIX'],plu:['POS PLU','POS_PLU','OD_POS_PLU','OD_POS PLU','OD_PLU'],barcode:['POS MASTER BARCODE','POS_MASTER_BARCODE','OD_MASTER_BARCODE','OD_MASTER BARCODE','OD_BARCODE'],description:['POS DESCR','POS_DESCR','POS DESCRIPTION','OD_POS_DESCR','OD_POS DESCR'],discount:['POS DISCOUNT%','POS DISCOUNT %','POS_DISCOUNT_PCT','OD_DISCOUNT %','OD_DISCOUNT_PCT'],markup:['POS MARKUP%','POS MARKUP %','POS_MARKUP_PCT','OD_MARKUP %','OD_MARKUP_PCT']};
function detectDiscountRows(rows){let ri=0;for(let i=0;i<Math.min(10,rows.length);i++){let vals=(rows[i]||[]).map(normHead);if(vals.some(v=>DHEAD.discount.some(a=>normHead(a)===v))){ri=i;break}}let raw=rows[ri]||[],headers=raw.map(v=>String(v??'').trim()),map={};for(const [k,aliases] of Object.entries(DHEAD)){let au=aliases.map(normHead);for(let i=0;i<headers.length;i++){if(au.includes(normHead(headers[i]))){map[k]=i;break}}}return{headerRow:ri,headers,map,data:rows.slice(ri+1)}}
function buildDiscountRules(rows,posRows,posHeaders){let d=detectDiscountRows(rows),r={supplier:new Map(),brand:[],prefix:[],plu:[],barcode:[],supplierBrand:new Map(),summary:{headerRow:d.headerRow+1,total:0}};if(d.map.discount===undefined)return r;let pc=findCols(posHeaders,'pos'),supBrands=new Map();for(const rr of posRows){let o=rowObj(posHeaders,rr),sid=int(o[pc.supplier_id]),br=cleanBrand(o[pc.brand]);if(sid&&br){if(!supBrands.has(sid))supBrands.set(sid,new Set());supBrands.get(sid).add(br)}}function bestMap(mp,k,val){let old=mp.get(k);if(!old||val[0]<old[0])mp.set(k,val)}function bestArr(arr,key,val){let old=arr.find(x=>x.key===key);if(!old)arr.push({key,val});else if(val[0]<old.val[0])old.val=val}for(const row of d.data){let disc=pct(row[d.map.discount]);if(disc===null)continue;let mark=d.map.markup===undefined?null:pct(row[d.map.markup]);if(mark===null)mark=1-disc;if(disc<0||disc>1||mark<0||mark>1)continue;let val=[1-disc,mark],sid=d.map.supplier===undefined?null:int(row[d.map.supplier]),br=d.map.brand===undefined?'':cleanBrand(row[d.map.brand]),pre=d.map.prefix===undefined?'':cleanBrand(row[d.map.prefix]),plu=d.map.plu===undefined?'':cleanLookup(row[d.map.plu]),bc=d.map.barcode===undefined?'':cleanBarcode(row[d.map.barcode]);r.summary.total++;if(sid&&!br&&!pre&&!plu&&!bc){bestMap(r.supplier,sid,val);for(const b of supBrands.get(sid)||[])r.supplierBrand.set(b,sid)}if(br){bestArr(r.brand,br+'|'+(sid||''),val);if(sid&&!r.supplierBrand.has(br))r.supplierBrand.set(br,sid)}if(pre)bestArr(r.prefix,pre+'|'+(sid||''),val);if(plu)bestArr(r.plu,plu+'|'+(sid||''),val);if(bc)bestArr(r.barcode,bc+'|'+(sid||''),val)}return r}
function pickRule(arr,value,sid){if(!value)return[];let out=[];for(const x of arr){let [v,s]=x.key.split('|');if(v===value&&(!s||Number(s)===sid))out.push(x.val)}return out}
function rowObj(headers,row){let o={};headers.forEach((h,i)=>o[h]=row[i]===undefined||row[i]===null?'':row[i]);return o}
function pricing(m,pc,sc,uc,rules){rules=rules||{supplier:new Map(),brand:[],prefix:[],plu:[],barcode:[],supplierBrand:new Map()};let posW=num(m[pc.wsp]),last=num(m[pc.last_price]),posR=num(m[pc.rrp]),sid=int(m[pc.supplier_id]),pg=int(m[pc.gst]);let ch2=m.CH2_INDEX!==''?num(m[sc.wsp]):null,cr=m.CH2_INDEX!==''?num(m[sc.rrp]):null,cg=m.CH2_INDEX!==''?String(m[sc.gst]||'').trim().toUpperCase():'';let uw=m.UHP_INDEX!==''?num(m[uc.wsp]):null,ur=m.UHP_INDEX!==''?num(m[uc.rrp]):null,ug=m.UHP_INDEX!==''?String(m[uc.gst]||'').trim().toUpperCase():'';let opts=[];if(ch2>0)opts.push(['CH2',ch2]);if(uw>0)opts.push(['UHP',uw]);let src=null,bw=null;if(opts.length){opts.sort((a,b)=>a[1]-b[1]);src=opts[0][0];bw=opts[0][1]}let nr=src==='CH2'&&cr!==null?cr:src==='UHP'&&ur!==null?ur:cr!==null?cr:ur;let gst=ug||cg||(pg!==null?(pg>0?'Y':'N'):'');let brand=cleanBrand(m.MASTER_BRAND),bc=cleanBarcode(m.MASTER_BARCODE),plu=String(m.MASTER_POS_PLU??'').trim(),eff=sid,inferred=false;if(!eff&&brand&&rules.supplierBrand?.has(brand)){eff=rules.supplierBrand.get(brand);inferred=true}let cand=[];if(eff&&rules.supplier?.has(eff))cand.push([inferred?'SUPPLIER (Brand Match)':'SUPPLIER (POS)',rules.supplier.get(eff)]);for(const v of pickRule(rules.brand||[],brand,eff))cand.push(['BRAND',v]);if(brand){let desc=cleanBrand([m[pc.description]||'',m[sc.description]||'',m[uc.description]||''].join(' '));for(const x of rules.prefix||[]){let [pre,s]=x.key.split('|');if(s&&Number(s)!==eff)continue;if(brand===pre||brand.startsWith(pre+' ')||desc.startsWith(pre+' '))cand.push(['BRAND',x.val])}}for(const v of pickRule(rules.plu||[],plu,eff))cand.push(['PLU',v]);for(const v of pickRule(rules.barcode||[],bc,eff))cand.push(['BARCODE',v]);let mult=1,mark=1,typ='NO DISCOUNT';if(cand.length){cand.sort((a,b)=>a[1][0]-b[1][0]);typ=cand[0][0];mult=cand[0][1][0];mark=cand[0][1][1]}let nw=bw,nl=bw!==null?(mult<1?bw*mult:bw):null,disp=mult<1?`${((1-mult)*100).toFixed(2)}% / ${(mark*100).toFixed(2)}%`:'';return{CURRENT_WSP:posW,NEW_WSP:nw,WSP_CHANGE_PCT:posW&&nw!==null?(nw-posW)/posW:null,'WSP_CHANGE_$':posW!==null&&nw!==null?nw-posW:null,CURRENT_LAST_PRICE:last,NEW_LAST_PRICE:nl,CHANGE_PCT_LAST_PRICE:last&&nl!==null?(nl-last)/last:null,'WSP_CHANGE_$_LAST_PRICE':last!==null&&nl!==null?nl-last:null,DISCOUNT_TYPE:typ,DISCOUNT_PCT:disp,CURRENT_RRP:posR,NEW_RRP:nr,HAS_GST:['Y','YES','TRUE','1','10%','0.1'].includes(String(gst).toUpperCase())?'Yes':'No'}}
function merge(pos,ph,ch,chh,uh,uhh,rules){const pc=findCols(ph,'pos'),sc=findCols(chh,'supplier'),uc=findCols(uhh,'uhp');let sb=new Map(),sco=new Map(),sbc=new Map(),ub=new Map(),uco=new Map(),ubc=new Map(),unique=new Map(); ch.forEach((r,i)=>{let o=rowObj(chh,r);o.CH2_INDEX=String(i+2);let bc=cleanBarcode(o[sc.barcode]),code=cleanCode(o[sc.code]),br=cleanBrand(o[sc.brand]);unique.set(o.CH2_INDEX,o);if(bc&&!sb.has(bc))sb.set(bc,o);if(code&&!sco.has(code))sco.set(code,o);if(br&&code&&!sbc.has(br+'|'+code))sbc.set(br+'|'+code,o)}); uh.forEach((r,i)=>{let o=rowObj(uhh,r);o.UHP_INDEX=String(i+2);let bc=cleanBarcode(o[uc.barcode]),code=cleanCode(o[uc.code]),br=cleanBrand(o[uc.brand]);if(bc&&!ub.has(bc))ub.set(bc,o);if(code&&!uco.has(code))uco.set(code,o);if(br&&code&&!ubc.has(br+'|'+code))ubc.set(br+'|'+code,o)});let usedS=new Set(),usedU=new Set(),out=[];pos.forEach((r,i)=>{let p=rowObj(ph,r),bc=cleanBarcode(p[pc.barcode]),code=cleanCode(p[pc.code]),plu=String(p[pc.plu]??'').trim(),br=cleanBrand(p[pc.brand]),sub=cleanCode(p[pc.sub_id]);let s=null,u=null,status='POS Only';if(bc&&sb.has(bc)){s=sb.get(bc);status='Barcode Match (CH2)'}else if(br&&sub&&sbc.has(br+'|'+sub)){s=sbc.get(br+'|'+sub);status='Brand+SubID Match (CH2)'}else if(code&&sco.has(code)&&brandsMatch(br,sco.get(code)[sc.brand])){s=sco.get(code);status='Code Match (CH2)'}if(s)usedS.add(s.CH2_INDEX);if(bc&&ub.has(bc)){u=ub.get(bc);status=status==='POS Only'?'Barcode Match (UHP)':status+' + UHP';usedU.add(bc)}else if(br&&sub&&ubc.has(br+'|'+sub)){u=ubc.get(br+'|'+sub);status=status==='POS Only'?'Brand+SubID Match (UHP)':status+' + UHP'}else if(code&&uco.has(code)&&brandsMatch(br,uco.get(code)[uc.brand])){u=uco.get(code);status=status==='POS Only'?'Code Match (UHP)':status+' + UHP'}let m=Object.assign({},p,s||{},u||{});m.POS_INDEX=i+2;m.CH2_INDEX=s?s.CH2_INDEX:'';m.UHP_INDEX=u?u.UHP_INDEX:'';m.AV_INDEX='';m.MATCH_STATUS=status;m.MASTER_BRAND=br;m.MASTER_BARCODE=bc;m.MASTER_POS_PLU=plu;Object.assign(m,pricing(m,pc,sc,uc,rules));out.push(m)});
for(const s of unique.values())if(s.CH2_INDEX&&!usedS.has(s.CH2_INDEX)){let bc=cleanBarcode(s[sc.barcode]),u=bc&&ub.get(bc)||null;if(u)usedU.add(bc);let m=Object.assign({},s,u||{});m.POS_INDEX='';m.CH2_INDEX=s.CH2_INDEX;m.UHP_INDEX=u?u.UHP_INDEX:'';m.MATCH_STATUS=u?'CH2 Only + UHP':'CH2 Only';m.MASTER_BRAND=cleanBrand(s[sc.brand]);m.MASTER_BARCODE=bc;m.MASTER_POS_PLU='';m.AV_INDEX='';Object.assign(m,pricing(m,pc,sc,uc,rules));out.push(m)}
for(const [bc,u] of ub)if(!usedU.has(bc)){let m=Object.assign({},u);m.POS_INDEX='';m.CH2_INDEX='';m.UHP_INDEX=u.UHP_INDEX;m.MATCH_STATUS='UHP Only';m.MASTER_BRAND=cleanBrand(u[uc.brand]);m.MASTER_BARCODE=bc;m.MASTER_POS_PLU='';m.AV_INDEX='';Object.assign(m,pricing(m,pc,sc,uc,rules));out.push(m)}return {rows:out,headers:SELECTED,keys:{pc,sc,uc}}}
g.MasterCore={SELECTED,SOH,findCols,cleanBarcode,cleanCode,cleanBrand,cleanLookup,brandsMatch,detectDiscountRows,buildDiscountRules,pricing,merge};
})(typeof window!=='undefined'?window:globalThis);
