(function(){
'use strict';
const C=window.UHPCore,VERSION='v1.0.0';
const state={uhp:null,brand:null,mainBlob:null,posBlob:null,mainName:'',posName:''};
const $=s=>document.querySelector(s),els={uhpInput:$('#uhpInput'),brandInput:$('#brandInput'),uhpDrop:$('#uhpDrop'),brandDrop:$('#brandDrop'),uhpFiles:$('#uhpFiles'),brandFiles:$('#brandFiles'),runBtn:$('#runBtn'),clearBtn:$('#clearBtn'),status:$('#status'),progress:$('#progress'),progressBar:$('#progressBar'),results:$('#results'),resultSub:$('#resultSub'),kpis:$('#kpis'),outputList:$('#outputList'),downloadMainBtn:$('#downloadMainBtn'),downloadPosBtn:$('#downloadPosBtn'),downloadBothBtn:$('#downloadBothBtn')};
function prettySize(b){if(b<1024)return `${b} B`;if(b<1048576)return `${(b/1024).toFixed(1)} KB`;return `${(b/1048576).toFixed(1)} MB`}
function setStatus(t,type='info'){els.status.className=`status ${type}`;els.status.textContent=t} function setProgress(v){els.progress.classList.remove('hidden');els.progressBar.style.width=`${v}%`} function hideProgress(){els.progress.classList.add('hidden');els.progressBar.style.width='0%'}
function fileRow(file,onRemove){const d=document.createElement('div');d.className='file-row';d.innerHTML=`<span><strong>${file.name}</strong> · ${prettySize(file.size)}</span>`;const b=document.createElement('button');b.textContent='Remove';b.onclick=onRemove;d.appendChild(b);return d}
function render(which){const el=els[which+'Files'];el.innerHTML='';if(state[which])el.appendChild(fileRow(state[which],()=>{state[which]=null;render(which);update()}))} function update(){els.runBtn.disabled=!state.uhp;setStatus(state.uhp?'UHP product export ready. Brand Abbreviation is optional.':'Add the Unique / UHP product export to continue.','info')}
function bind(which){const I=els[which+'Input'],D=els[which+'Drop'];const set=f=>{if(!f)return;state[which]=f;render(which);update()};D.onclick=()=>I.click();D.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();I.click()}};I.onchange=()=>set(I.files[0]);['dragenter','dragover'].forEach(ev=>D.addEventListener(ev,e=>{e.preventDefault();D.classList.add('drag')}));['dragleave','drop'].forEach(ev=>D.addEventListener(ev,e=>{e.preventDefault();D.classList.remove('drag')}));D.addEventListener('drop',e=>set(e.dataTransfer.files[0]));}
['uhp','brand'].forEach(bind);
async function readSheets(file){const wb=XLSX.read(await file.arrayBuffer(),{type:'array',raw:true,cellDates:false});return wb.SheetNames.map(name=>({name,rows:XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:null,raw:true,blankrows:true})}))}
async function brandMap(file){if(!file)return new Map();const rows=(await readSheets(file))[0]?.rows||[],m=new Map();for(const r of rows.slice(1)){if(r.length>=2&&r[0]!=null&&r[1]!=null){const a=C.cleanExcelText(r[0]).trim().toUpperCase(),b=C.cleanExcelText(r[1]).trim();if(a&&b)m.set(a,b)}}return m}
function addRows(ws,headers,rows,textHeaders){ws.addRow(headers);ws.getRow(1).font={bold:true};ws.getRow(1).alignment={wrapText:false,shrinkToFit:false,vertical:'middle'};rows.forEach(r=>ws.addRow(r));ws.autoFilter={from:{row:1,column:1},to:{row:Math.max(1,ws.rowCount),column:headers.length}};ws.views=[{state:'frozen',ySplit:1}];ws.eachRow({includeEmpty:true},(row,n)=>{row.height=15;row.eachCell({includeEmpty:true},cell=>{if(n>1)cell.alignment={wrapText:false,shrinkToFit:false,vertical:'top'}})});headers.forEach((h,i)=>{if(textHeaders.has(h))ws.getColumn(i+1).eachCell({includeEmpty:true},c=>c.numFmt='@')})}
async function makeWorkbook(sheet,headers,rows,textHeaders){const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet(sheet);addRows(ws,headers,rows,textHeaders);return new Blob([await wb.xlsx.writeBuffer()],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}
function cv(v){return v==null?'':v} function equal(a,b){a=cv(a);b=cv(b);if(typeof a==='number'&&typeof b==='number')return Math.abs(a-b)<1e-12;return String(a)===String(b)}
async function verify(blob,sheetName,headers,rows,textHeaders){const wb=XLSX.read(await blob.arrayBuffer(),{type:'array',raw:true,cellNF:true}),ws=wb.Sheets[sheetName];if(!ws||wb.SheetNames.length!==1)throw new Error(`${sheetName}: worksheet structure mismatch.`);const m=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:true,blankrows:true});if(m.length!==rows.length+1)throw new Error(`${sheetName}: expected ${rows.length} rows, got ${m.length-1}.`);if(headers.length!==(m[0]||[]).length||headers.some((h,i)=>String(m[0][i]??'')!==h))throw new Error(`${sheetName}: exported columns do not exactly match the required layout.`);for(let r=0;r<rows.length;r++)for(let c=0;c<headers.length;c++){if(!equal(m[r+1]?.[c]??'',rows[r][c]??''))throw new Error(`${sheetName}: integrity mismatch at row ${r+2}, column ${headers[c]}. Expected “${rows[r][c]??''}”, got “${m[r+1]?.[c]??''}”.`);if(textHeaders.has(headers[c])){const cell=ws[XLSX.utils.encode_cell({r:r+1,c})];if(cell&&cell.z!=='@')throw new Error(`${sheetName}: ${headers[c]} at row ${r+2} is missing Excel Text (@) format.`)}}}
function stamp(){const p=new Intl.DateTimeFormat('en-GB',{timeZone:'Australia/Melbourne',day:'2-digit',month:'2-digit',year:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date()),g=t=>p.find(x=>x.type===t)?.value||'';return {date:`${g('day')}.${g('month')}.${g('year')}`,time:`${g('hour')}${g('minute')}`}}
function dl(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1200)}
async function run(){if(!state.uhp)return;els.runBtn.disabled=true;els.results.classList.add('hidden');try{setStatus('Reading Unique / UHP product export…');setProgress(12);const sheets=await readSheets(state.uhp),parsed=C.parseUhpRows(sheets[0]?.rows||[]);setProgress(28);const bm=await brandMap(state.brand),proc=C.processUhp(parsed.headers,parsed.rows,bm),posRows=C.buildSupplierImport(proc.headers,proc.rows);setProgress(58);setStatus('Building and validating both Excel outputs…');const mainText=new Set(proc.headers.filter(h=>['BARCODE','APN','EAN','UPC'].some(k=>h.toUpperCase().includes(k)))),posText=new Set(['SUP BARCODE','SUP SUB ID']);const mainBlob=await makeWorkbook('UHP_Data',proc.headers,proc.rows,mainText);setProgress(76);const posBlob=await makeWorkbook('IN_SUPPLIER_UPDATE',C.SUPPLIER_IMPORT_HEADERS,posRows,posText);setProgress(88);await verify(mainBlob,'UHP_Data',proc.headers,proc.rows,mainText);await verify(posBlob,'IN_SUPPLIER_UPDATE',C.SUPPLIER_IMPORT_HEADERS,posRows,posText);const st=stamp();state.mainName=`clean_uhp_data_${VERSION}_${st.date}_${st.time}.xlsx`;state.posName=`clean_uhp_data_pos_db_${VERSION}_${st.date}_${st.time}.xlsx`;state.mainBlob=mainBlob;state.posBlob=posBlob;els.resultSub.textContent=`${proc.rows.length.toLocaleString()} Unique / UHP rows · source header row ${parsed.headerIdx+1} · 2 / 2 workbooks verified`;els.kpis.innerHTML=`<div class="kpi"><strong>${proc.rows.length.toLocaleString()}</strong><span>UHP PRODUCT ROWS</span></div><div class="kpi"><strong>${parsed.headers.length}</strong><span>SOURCE COLUMNS</span></div><div class="kpi"><strong>${proc.headers.length}</strong><span>MAIN OUTPUT COLUMNS</span></div><div class="kpi"><strong>16</strong><span>POS DB COLUMNS</span></div><div class="kpi"><strong>${proc.brandSubstitutions.toLocaleString()}</strong><span>BRAND SUBSTITUTIONS</span></div>`;els.outputList.innerHTML=`<div class="output-row"><code>${state.mainName}</code><span>${proc.headers.length} columns · ${proc.rows.length.toLocaleString()} rows · verified</span></div><div class="output-row"><code>${state.posName}</code><span>16 columns · ${posRows.length.toLocaleString()} rows · verified</span></div>`;els.results.classList.remove('hidden');setProgress(100);setStatus('Complete — 2 / 2 outputs verified against the calculated Unique / UHP model.','success');setTimeout(hideProgress,500)}catch(e){console.error(e);hideProgress();setStatus(`Error: ${e.message}`,'error')}finally{update();els.runBtn.disabled=!state.uhp}}
els.runBtn.onclick=run;els.clearBtn.onclick=()=>{Object.assign(state,{uhp:null,brand:null,mainBlob:null,posBlob:null});['uhp','brand'].forEach(render);els.results.classList.add('hidden');update()};els.downloadMainBtn.onclick=()=>state.mainBlob&&dl(state.mainBlob,state.mainName);els.downloadPosBtn.onclick=()=>state.posBlob&&dl(state.posBlob,state.posName);els.downloadBothBtn.onclick=()=>{if(state.mainBlob&&state.posBlob){dl(state.mainBlob,state.mainName);setTimeout(()=>dl(state.posBlob,state.posName),500)}};update();
})();
